// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
];

const customers = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442a',
    name: 'Delba de Oliveira',
    email: 'delba@oliveira.com',
    image_url: '/customers/delba-de-oliveira.png',
  },
  {
    id: '3958dc9e-742f-4377-85e9-fec4b6a6442a',
    name: 'Lee Robinson',
    email: 'lee@robinson.com',
    image_url: '/customers/lee-robinson.png',
  },
  {
    id: '3958dc9e-737f-4377-85e9-fec4b6a6442a',
    name: 'Hector Simpson',
    email: 'hector@simpson.com',
    image_url: '/customers/hector-simpson.png',
  },
  {
    id: '50ca3e18-62cd-11ee-8c99-0242ac120002',
    name: 'Steven Tey',
    email: 'steven@tey.com',
    image_url: '/customers/steven-tey.png',
  },
  {
    id: '3958dc9e-787f-4377-85e9-fec4b6a6442a',
    name: 'Steph Dietz',
    email: 'steph@dietz.com',
    image_url: '/customers/steph-dietz.png',
  },
  {
    id: '76d65c26-f784-44a2-ac19-586678f7c2f2',
    name: 'Michael Novotny',
    email: 'michael@novotny.com',
    image_url: '/customers/michael-novotny.png',
  },
  {
    id: 'd6e15727-9fe1-4961-8c5b-ea44a9bd81aa',
    name: 'Evil Rabbit',
    email: 'evil@rabbit.com',
    image_url: '/customers/evil-rabbit.png',
  },
  {
    id: '126eed9c-c90c-4ef6-a4a8-fcf7408d3c66',
    name: 'Emil Kowalski',
    email: 'emil@kowalski.com',
    image_url: '/customers/emil-kowalski.png',
  },
  {
    id: 'CC27C14A-0ACF-4F4A-A6C9-D45682C144B9',
    name: 'Amy Burns',
    email: 'amy@burns.com',
    image_url: '/customers/amy-burns.png',
  },
  {
    id: '13D07535-C59E-4157-A011-F8D2EF4E0CBB',
    name: 'Balazs Orban',
    email: 'balazs@orban.com',
    image_url: '/customers/balazs-orban.png',
  },
];

const invoices = [
  {
    customer_id: customers[0].id,
    amount: 15795,
    status: 'pending',
    date: '2022-12-06',
  },
  {
    customer_id: customers[1].id,
    amount: 20348,
    status: 'pending',
    date: '2022-11-14',
  },
  {
    customer_id: customers[4].id,
    amount: 3040,
    status: 'paid',
    date: '2022-10-29',
  },
  {
    customer_id: customers[3].id,
    amount: 44800,
    status: 'paid',
    date: '2023-09-10',
  },
  {
    customer_id: customers[5].id,
    amount: 34577,
    status: 'pending',
    date: '2023-08-05',
  },
  {
    customer_id: customers[7].id,
    amount: 54246,
    status: 'pending',
    date: '2023-07-16',
  },
  {
    customer_id: customers[6].id,
    amount: 666,
    status: 'pending',
    date: '2023-06-27',
  },
  {
    customer_id: customers[3].id,
    amount: 32545,
    status: 'paid',
    date: '2023-06-09',
  },
  {
    customer_id: customers[4].id,
    amount: 1250,
    status: 'paid',
    date: '2023-06-17',
  },
  {
    customer_id: customers[5].id,
    amount: 8546,
    status: 'paid',
    date: '2023-06-07',
  },
  {
    customer_id: customers[1].id,
    amount: 500,
    status: 'paid',
    date: '2023-08-19',
  },
  {
    customer_id: customers[5].id,
    amount: 8945,
    status: 'paid',
    date: '2023-06-03',
  },
  {
    customer_id: customers[2].id,
    amount: 8945,
    status: 'paid',
    date: '2023-06-18',
  },
  {
    customer_id: customers[0].id,
    amount: 8945,
    status: 'paid',
    date: '2023-10-04',
  },
  {
    customer_id: customers[2].id,
    amount: 1000,
    status: 'paid',
    date: '2022-06-05',
  },
];

const revenue = [
  { month: 'Jan', revenue: 2000 },
  { month: 'Feb', revenue: 1800 },
  { month: 'Mar', revenue: 2200 },
  { month: 'Apr', revenue: 2500 },
  { month: 'May', revenue: 2300 },
  { month: 'Jun', revenue: 3200 },
  { month: 'Jul', revenue: 3500 },
  { month: 'Aug', revenue: 3700 },
  { month: 'Sep', revenue: 2500 },
  { month: 'Oct', revenue: 2800 },
  { month: 'Nov', revenue: 3000 },
  { month: 'Dec', revenue: 4800 },
];

const activite = [
  {
    id:1,
    Nom_du_POI: 'Visite de la cave du Château de Calavon',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#EntertainmentAndEvent|https://www.datatourisme.fr/ontology/core#PointOfInterest|https://www.datatourisme.fr/ontology/core#Product|https://www.datatourisme.fr/ontology/core#Visit|http://schema.org/Event|http://schema.org/Product',
    Latitude: 43.655,
    Longitude: 5.259444,
    Adresse_postale: '12 Avenue de Badonviller Château de Calavon',
    Code_postal_et_commune: '13410#Lambesc',
    Createur_de_la_donnee: 'Bureau municipal du Tourisme de Lambesc',
    SIT_diffuseur: 'Provence Tourisme / Maison du Tourisme de Lambesc',
    Date_de_mise_a_jour: '2023-04-21',
    Contacts_du_POI: '#+33 4 42 57 15 37#contact@chateaudecalavon.com#http://www.chateaudecalavon.com/|Château de Calavon###https://www.lesgrappes.com/vignerons/u/chateaudecalavon/visites-degustations|Château de Calavon#+33 4 42 57 15 37##',
    Classements_du_POI: 'Vignobles & Découvertes#Label Vignobles & Découvertes',
    Description: 'Le Château de Calavon vous ouvre ses portes pour une visite de la cave et une présentation des ses différentes cuvées.',
    URI_ID_du_POI: 'https://data.datatourisme.fr/58/b1ea827e-1ffc-3fa3-b686-3d640b39c0b1'
  },
  {
    id:2,
    Nom_du_POI: 'Visite de la cave du Château de Calavon',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#EntertainmentAndEvent|https://www.datatourisme.fr/ontology/core#PointOfInterest|https://www.datatourisme.fr/ontology/core#Product|https://www.datatourisme.fr/ontology/core#Visit|http://schema.org/Event|http://schema.org/Product',
    Latitude: 43.655,
    Longitude: 5.259444,
    Adresse_postale: '12 Avenue de Badonviller Château de Calavon',
    Code_postal_et_commune: '13410#Lambesc',
    Createur_de_la_donnee: 'Maison du Tourisme de Lambesc',
    SIT_diffuseur: 'Provence Tourisme / Maison du Tourisme de Lambesc',
    Date_de_mise_a_jour: '2023-04-21',
    Contacts_du_POI: '#+33 4 42 57 15 37#contact@chateaudecalavon.com#http://www.chateaudecalavon.com/|Château de Calavon###https://www.lesgrappes.com/vignerons/u/chateaudecalavon/visites-degustations|Château de Calavon#+33 4 42 57 15 37##',
    Classements_du_POI: 'Vignobles & Découvertes#Label Vignobles & Découvertes',
    Description: 'Le Château de Calavon vous ouvre ses portes pour une visite de la cave et une présentation des ses différentes cuvées.',
    URI_ID_du_POI: 'https://data.datatourisme.fr/58/b1ea827e-1ffc-3fa3-b686-3d640b39c0b1'
  },
  {
    id:3,
    Nom_du_POI: 'Restaurant Lou Pountin',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#FoodEstablishment|https://www.datatourisme.fr/ontology/core#PlaceOfInterest|https://www.datatourisme.fr/ontology/core#PointOfInterest|http://schema.org/FoodEstablishment',
    Latitude: 43.987579,
    Longitude: 7.552608,
    Adresse_postale: '56 rue Lieutenant Revelli',
    Code_postal_et_commune: '06540#Saorge',
    Createur_de_la_donnee: 'Office de Tourisme Menton Riviera Merveilles',
    SIT_diffuseur: 'Apidae Tourisme Scic SA - source : Apidae Tourisme',
    Date_de_mise_a_jour: '2023-01-07',
    Contacts_du_POI: '#+33 4 97 20 15 94#loupountin06@gmail.com#',
    Classements_du_POI: 'Accueil Vélo#France Vélo Tourisme',
    Description: 'Joli restaurant et bar à tapas typique avec petite terrasse, au centre de Saorge,  fascinant village médiéval piéton. Une nouvelle énergie avec une nouvelle équipe, heureuse de vous accueillir.',
    URI_ID_du_POI: 'https://data.datatourisme.fr/13/ac7d641c-1685-3a68-a2f4-867fbc77914a'
  },
  {
    id:4,
    Nom_du_POI: 'Novotel Marseille Centre Prado Vélodrome',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#FoodEstablishment|https://www.datatourisme.fr/ontology/core#PlaceOfInterest|https://www.datatourisme.fr/ontology/core#PointOfInterest|https://www.datatourisme.fr/ontology/core#Restaurant|https://www.datatourisme.fr/ontology/core#Accommodation|https://www.datatourisme.fr/ontology/core#Hotel|https://www.datatourisme.fr/ontology/core#HotelRestaurant|https://www.datatourisme.fr/ontology/core#HotelTrade|http://schema.org/Accommodation|http://schema.org/FoodEstablishment|http://schema.org/LodgingBusiness|http://schema.org/Restaurant|http://schema.org/Hotel',
    Latitude: 43.280925,
    Longitude: 5.386912,
    Adresse_postale: '103 Avenue Du Prado',
    Code_postal_et_commune: '13008#Marseille 8e Arrondissement',
    Createur_de_la_donnee: 'Office Métropolitain de tourisme et des congrès de Marseille',
    SIT_diffuseur: 'Provence Tourisme / Office de Tourisme des Loisirs et des Congrès de Marseille',
    Date_de_mise_a_jour: '2023-10-23',
    Contacts_du_POI: '#+33 4 91 83 10 10#h9013@accor.com#https://all.accor.com/hotel/9013/index.fr.shtml',
    Classements_du_POI: '4 étoiles#Classement officiel des hébergements touristiques|Clef Verte#Clef verte',
    Description: 'Proche du bord de mer, des rues commerçantes et du centre historique, cet hôtel bénéficie d"un cadre agréable et d"un accès direct grâce au tunnel Prado Carénage et aux axes autoroutiers principaux (A7, A50).',
    URI_ID_du_POI: 'https://data.datatourisme.fr/58/098b1b72-cc07-3d6c-b3a8-443c3ef08214'
  },
  {
    id:5,
    Nom_du_POI: 'Novotel Marseille Centre Prado Vélodrome',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#FoodEstablishment|https://www.datatourisme.fr/ontology/core#PlaceOfInterest|https://www.datatourisme.fr/ontology/core#PointOfInterest|https://www.datatourisme.fr/ontology/core#Restaurant|https://www.datatourisme.fr/ontology/core#Accommodation|https://www.datatourisme.fr/ontology/core#Hotel|https://www.datatourisme.fr/ontology/core#HotelRestaurant|https://www.datatourisme.fr/ontology/core#HotelTrade|http://schema.org/Accommodation|http://schema.org/FoodEstablishment|http://schema.org/LodgingBusiness|http://schema.org/Restaurant|http://schema.org/Hotel',
    Latitude: 43.280925,
    Longitude: 5.386912,
    Adresse_postale: '103 Avenue Du Prado',
    Code_postal_et_commune: '13008#Marseille 8e Arrondissement',
    Createur_de_la_donnee: 'Office de tourisme et des congrès de Marseille',
    SIT_diffuseur: 'Provence Tourisme / Office de Tourisme des Loisirs et des Congrès de Marseille',
    Date_de_mise_a_jour: '2023-10-23',
    Contacts_du_POI: '#+33 4 91 83 10 10#h9013@accor.com#https://all.accor.com/hotel/9013/index.fr.shtml',
    Classements_du_POI: '4 étoiles#Classement officiel des hébergements touristiques|Clef Verte#Clef verte',
    Description: 'Proche du bord de mer, des rues commerçantes et du centre historique, cet hôtel bénéficie d"un cadre agréable et d"un accès direct grâce au tunnel Prado Carénage et aux axes autoroutiers principaux (A7, A50).',
    URI_ID_du_POI: 'https://data.datatourisme.fr/58/098b1b72-cc07-3d6c-b3a8-443c3ef08214'
  },
  {
    id:6,
    Nom_du_POI: 'Novotel Marseille Centre Prado Vélodrome',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#FoodEstablishment|https://www.datatourisme.fr/ontology/core#PlaceOfInterest|https://www.datatourisme.fr/ontology/core#PointOfInterest|https://www.datatourisme.fr/ontology/core#Restaurant|https://www.datatourisme.fr/ontology/core#Accommodation|https://www.datatourisme.fr/ontology/core#Hotel|https://www.datatourisme.fr/ontology/core#HotelRestaurant|https://www.datatourisme.fr/ontology/core#HotelTrade|http://schema.org/Accommodation|http://schema.org/FoodEstablishment|http://schema.org/LodgingBusiness|http://schema.org/Restaurant|http://schema.org/Hotel',
    Latitude: 43.280925,
    Longitude: '5.386912',
    Adresse_postale: '103 Avenue Du Prado',
    Code_postal_et_commune: '13008#Marseille 8e Arrondissement',
    Createur_de_la_donnee: 'Office de Tourisme des Loisirs et des Congrès de Marseille',
    SIT_diffuseur: 'Provence Tourisme / Office de Tourisme des Loisirs et des Congrès de Marseille',
    Date_de_mise_a_jour: '2023-10-23',
    Contacts_du_POI: '#+33 4 91 83 10 10#h9013@accor.com#https://all.accor.com/hotel/9013/index.fr.shtml',
    Classements_du_POI: '4 étoiles#Classement officiel des hébergements touristiques|Clef Verte#Clef verte',
    Description: 'Proche du bord de mer, des rues commerçantes et du centre historique, cet hôtel bénéficie d"un cadre agréable et d"un accès direct grâce au tunnel Prado Carénage et aux axes autoroutiers principaux (A7, A50).',
    URI_ID_du_POI: 'https://data.datatourisme.fr/58/098b1b72-cc07-3d6c-b3a8-443c3ef08214'
  },
  {
    id:7,
    Nom_du_POI: 'Hôtel le Chalet Fleuri',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#PlaceOfInterest|https://www.datatourisme.fr/ontology/core#PointOfInterest|https://www.datatourisme.fr/ontology/core#Accommodation|https://www.datatourisme.fr/ontology/core#Hotel|https://www.datatourisme.fr/ontology/core#HotelTrade|http://schema.org/Accommodation|http://schema.org/LodgingBusiness|http://schema.org/Hotel',
    Latitude: 43.79207,
    Longitude: 4.830224,
    Adresse_postale: '15 Avenue Frédéric Mistral',
    Code_postal_et_commune: '13210#Saint-Rémy-de-Provence',
    Createur_de_la_donnee: 'Régie Tourisme de la CC Vallée Des Baux-Alpilles',
    SIT_diffuseur: 'Provence Tourisme / Régie Tourisme de la CC Vallée Des Baux-Alpilles',
    Date_de_mise_a_jour: '2023-02-10',
    Contacts_du_POI: '#+33 4 90 92 03 62#contact@hotel-lechaletfleuri.com#https://www.hotel-lechaletfleuri.com/',
    Classements_du_POI: '3 étoiles#Classement officiel des hébergements touristiques',
    Description: 'L’Hôtel de charme le Chalet Fleuri situé à seulement 150 mètres du centre historique de Saint Rémy de Provence, village typiquement provençal ayant su préserver son authenticité, sa douceur de vivre et ses traditions.',
    URI_ID_du_POI: 'https://data.datatourisme.fr/58/09973111-bd67-3feb-8991-6b3373829b92'
  },
  {
    id:8,
    Nom_du_POI: 'Mercure Marseille Centre Vieux Port',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#FoodEstablishment|https://www.datatourisme.fr/ontology/core#PlaceOfInterest|https://www.datatourisme.fr/ontology/core#PointOfInterest|https://www.datatourisme.fr/ontology/core#Restaurant|https://www.datatourisme.fr/ontology/core#Accommodation|https://www.datatourisme.fr/ontology/core#Hotel|https://www.datatourisme.fr/ontology/core#HotelRestaurant|https://www.datatourisme.fr/ontology/core#HotelTrade|http://schema.org/Accommodation|http://schema.org/FoodEstablishment|http://schema.org/LodgingBusiness|http://schema.org/Restaurant|http://schema.org/Hotel',
    Latitude: 43.298775,
    Longitude: 5.37462,
    Adresse_postale: '1 Rue Neuve Saint-Martin',
    Code_postal_et_commune: '13001#Marseille 1er Arrondissement',
    Createur_de_la_donnee: 'Office Métropolitain de tourisme et des congrès de Marseille',
    SIT_diffuseur: 'Provence Tourisme / Office de Tourisme des Loisirs et des Congrès de Marseille',
    Date_de_mise_a_jour: '2023-10-24',
    Contacts_du_POI: '#+33 4 96 17 22 22#h1148@accor.com#http://www.mercure-marseille-centre-vieux-port.com/',
    Classements_du_POI: '4 étoiles#Classement officiel des hébergements touristiques|Clef Verte#Clef verte',
    Description: 'Situé au cœur du cente ville à proximité du Vieux Port et centre commercial Bourse. Un hôtel 4**** de 200 chambres au cœur de la ville, doté de plus de 1350 m2 de salles de réunion dans une ambiance moderne et contemporaine.',
    URI_ID_du_POI: 'https://data.datatourisme.fr/58/13bb07fb-10e5-3d9d-89bc-286490164347'
  },
  {
    id:9,
    Nom_du_POI: 'Mercure Marseille Centre Vieux Port',
    Categories_de_POI: 'https://www.datatourisme.fr/ontology/core#FoodEstablishment|https://www.datatourisme.fr/ontology/core#PlaceOfInterest|https://www.datatourisme.fr/ontology/core#PointOfInterest|https://www.datatourisme.fr/ontology/core#Restaurant|https://www.datatourisme.fr/ontology/core#Accommodation|https://www.datatourisme.fr/ontology/core#Hotel|https://www.datatourisme.fr/ontology/core#HotelRestaurant|https://www.datatourisme.fr/ontology/core#HotelTrade|http://schema.org/Accommodation|http://schema.org/FoodEstablishment|http://schema.org/LodgingBusiness|http://schema.org/Restaurant|http://schema.org/Hotel',
    Latitude: 43.298775,
    Longitude: 5.37462,
    Adresse_postale: '1 Rue Neuve Saint-Martin',
    Code_postal_et_commune: '13001#Marseille 1er Arrondissement',
    Createur_de_la_donnee: 'Office de tourisme et des congrès de Marseille',
    SIT_diffuseur: 'Provence Tourisme / Office de Tourisme des Loisirs et des Congrès de Marseille',
    Date_de_mise_a_jour: '2023-10-24',
    Contacts_du_POI: '#+33 4 96 17 22 22#h1148@accor.com#http://www.mercure-marseille-centre-vieux-port.com/',
    Classements_du_POI: '4 étoiles#Classement officiel des hébergements touristiques|Clef Verte#Clef verte',
    Description: 'Situé au cœur du cente ville à proximité du Vieux Port et centre commercial Bourse. Un hôtel 4**** de 200 chambres au cœur de la ville, doté de plus de 1350 m2 de salles de réunion dans une ambiance moderne et contemporaine.',
    URI_ID_du_POI: 'https://data.datatourisme.fr/58/13bb07fb-10e5-3d9d-89bc-286490164347'
  },
];

module.exports = {
  users,
  customers,
  invoices,
  revenue,
  activite,
};