// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data

const activite = [
  {
      image: 'https://www.nice.fr/uploads/media/paysage/0001/01/musee_matisse_1.jpg',
      title: 'Musée Matisse',
      description: 'Le musée Matisse à Nice est dédié au célèbre artiste Henri Matisse.',
      ville: 'Nice',
      longitude: 7.2551,
      latitude: 43.7102,
      budget: 10,
      rating: 4.5,
      type: 'Musée',
      parcours: false,
  },
  {
      image: 'https://www.francebleu.fr/s3/cruiser-production/2023/09/9bdf8760-955b-4228-9374-1f48fec93491/1200x680_sc_csm-header-nice-patrimoine-188bdb26bd.jpg',
      title: 'Promenade des Anglais',
      description: "La Promenade des Anglais est l'endroit idéal pour une belle balade au bord de la mer.",
      ville: 'Nice',
      longitude: 6.2510,
      latitude: 43.6950,
      budget: 0,
      rating: 4.8,
      type: 'Extérieur',
      parcours: false,
  },
  {
      image: 'https://cdn.getyourguide.com/img/tour/58eb86acaeeb1.jpeg/98.jpg',
      title: 'Vieux-Nice',
      description: 'Le Vieux-Nice est un quartier pittoresque avec des rues étroites, des marchés et de la cuisine délicieuse.',
      ville: 'Nice',
      longitude: 7.2770,
      latitude: 43.6974,
      budget: 0,
      rating: 4.3,
      type: 'Extérieur',
      parcours: false,
  },
  {
      image: 'https://www.geolithe.fr/wp-content/uploads/2020/04/Pano1-scaled.jpg',
      title: 'Colline du Château',
      description: "La Colline du Château offre une vue panoramique sur la ville de Nice et la Méditerranée.",
      ville: 'Nice',
      longitude: 7.2872,
      latitude: 43.6973,
      budget: 0,
      rating: 4.6,
      type: 'Chateau',
      parcours: false,
  },
  {
      image: 'https://frenchriviera.travel/wp-content/uploads/2018/09/Parc-Phoenix1.jpg',
      title: 'Parc Phoenix',
      description: 'Le Parc Phoenix est un jardin botanique et un parc zoologique à Nice.',
      ville: 'Nice',
      longitude: 7.2073,
      latitude: 43.6622,
      budget: 5,
      rating: 4.4,
      type: 'Zoo',
      parcours: false,
  },
  {
    image: 'https://static.apidae-tourisme.com/filestore/objets-touristiques/images/6/3/12714758.jpg',
    title: 'Cours Saleya',
    description: 'Le Cours Saleya est un marché en plein air à Nice, idéal pour les produits locaux et les souvenirs.',
    ville: 'Nice',
    longitude: 7.2774,
    latitude: 43.6966,
    budget: 0,
    rating: 4.2,
    type: 'Exterieur',
    parcours: false,
  },
  {
    image: 'https://www.opera-nice.org/media/image/cms/media/Contenu_statique/salle-opera.jpg',
    title: 'Opéra de Nice',
    description: 'L\'Opéra de Nice est un lieu prestigieux pour les arts du spectacle et l opéra.',
    ville: 'Nice',
    longitude: 7.2640,
    latitude: 43.6960,
    budget: 30,
    rating: 4.6,
    type: 'Opera',
    parcours: false,
  },
  {
    image: 'https://lespepitesdefrance.com/wp-content/uploads/2022/03/1646961098_63_Marche-du-Cours-Saleya-a-Nice-France.jpg',
    title: 'Marché aux Fleurs de Nice',
    description: 'Le Marché aux Fleurs est un endroit pittoresque pour acheter des fleurs, des plantes et des produits locaux.',
    ville: 'Nice',
    longitude: 7.2727,
    latitude: 43.6971,
    budget: 0,
    rating: 4.3,
    type: 'Exterieur',
    parcours: false,
  },
  {
    image: 'https://woody.cloudly.space/app/uploads/crt-paca/2021/12/thumbs/mamac-nice-saiko3p-as-1920x960.jpg',
    title: 'Musée d\'Art Moderne et d\'Art Contemporain (MAMAC)',
    description: 'Le MAMAC présente des œuvres d\'art moderne et contemporain, notamment des artistes niçois.',
    ville: 'Nice',
    longitude: 7.2870,
    latitude: 43.7037,
    budget: 10,
    rating: 4.0,
    type: 'Musée',
    parcours: false,
  },
  {
    image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/e5/dd/22/photo2jpg.jpg?w=1200&h=-1&s=1',
    title: 'Cathédrale Saint-Nicolas',
    description: 'La cathédrale Saint-Nicolas est un exemple d\'architecture religieuse magnifique à Nice.',
    ville: 'Nice',
    longitude: 7.2617,
    latitude: 43.7027,
    budget: 0,
    rating: 4.5,
    type: 'Religieux',
    parcours: false,
  },
  {
    image: 'https://medias.lejourduseigneur.com/2023/01/33ffd0f4f14d9046b3203fc8c2eaa237.jpg',
    title: 'Basilique Notre-Dame de la Garde',
    description: 'La basilique Notre-Dame de la Garde. Figure emblématique de la Ville de Marseille, elle veille sur les marins, les pêcheurs et tous les Marseillais',
    ville: 'Marseille',
    longitude: 5.371423758723082,
    latitude: 43.28514568785665, 
    budget: 0,
    rating: 4.7,
    type: 'Religieux',
    parcours: false,
  },
  {
    image: 'https://www.marseille-tourisme.com/app/uploads/marseille-tourisme/2020/06/thumbs/palais-longchamp-leotcm-1920x960.jpg',
    title: 'Palais Longchamp',
    description: 'Monument datant du milieu du XIXe siècle, avec une cascade et un réservoir construits pour alimenter en eau la ville.',
    ville: 'Marseille',
    longitude: 5.394871118104645,
    latitude: 43.30434494713965,
    budget: 4,
    rating: 4.5,
    type: 'Monument',
    parcours: false,
  },
  {
    image: 'https://www.marseille-tourisme.com/app/uploads/marseille-tourisme/2020/11/thumbs/mucem-fort-saint-jean-vieux-porte-lamyomtcm-taille-reduite-1920x960.jpg',
    title: 'Vieux-Port',
    description: 'C\'est un port de plaisance entouré par le quartier de l\'Hôtel de Ville, de l\'Opéra, de Saint-Victor et du Pharo.',
    ville: 'Marseille',
    longitude: 5.591057340905156,
    latitude: 43.348413886686345,
    budget: 0,
    rating: 4.5,
    type: 'Exterieur',
    parcours: false,
  },
  {
    image: 'https://www.calanques-if.com/uploads/files/image-t-site1route-10.jpg',
    title: 'Parc national des Calanques',
    description: 'Le Parc national des Calanques est une aire marine et terrestre protégée de Méditerranée.',
    ville: 'Marseille',
    longitude: 5.443114356306976,
    latitude: 43.217991535540406,
    budget: 0,
    rating: 4.7,
    type: 'Exterieur',
    parcours: false,
  },
  {
    image: 'https://res.cloudinary.com/hzekpb1cg/image/upload/q_95,f_auto/s3/public/prod/s3fs-public/Frioul1000.jpg',
    title: 'Château d\'If',
    description: 'Le château d\'If est une forteresse française édifiée sur les ordres du roi François Iᵉʳ',
    ville: 'Marseille',
    longitude: 5.325000166098952,
    latitude: 43.279987955659315,
    budget: 6,
    rating: 4.4,
    type: 'Chateau',
    parcours: false,
  }
];

module.exports = {
  activite,
};